### ISSUE TITLE
Please tell how to run inference.

### ISSUE THREAD

**Issue by charchit7** [littlewhitesea/StitchDiffusion#2]
Colab notebook is not working. If you guys could please guide on how to generate images that would really help. 
Thanks :)

**Comment by littlewhitesea** [comment]
Hi, thanks for your interest in our work.

I just ran the google colab. It seems that there are some problems with the "gdown" in the Step 3.

You can use the following codes:

```
!pip install wget
import wget

# URL of the pre-trained LoRA file on Google Drive
lora_url = "https://drive.google.com/u/0/uc?id=1MiaG8v0ZmkTwwrzIEFtVoBj-Jjqi_5lz&export=download"

# Destination path to save the downloaded file
lora_save_path = "/content/lora.safetensors"

# Download the file using wget
wget.download(lora_url, lora_save_path)

# download test file
!wget -O /content/kohya-trainer/stitchdiffusion_test.py https://raw.githubusercontent.com/lshus/stitchdiffusion-colab/main/stitchdiffusion_test.py
```

It should work. If you have any other questions, please feel free to let me know.

**Comment by charchit7** [comment]
This code will also not work. I think the reason is drive gives temp name to the file being downloaded : for eg. `1h7e_zst.tmp` or `1h7e_zst.tmp6bi7gfr5.tmp` in the first place and after download it fully restores.

I downloaded using `wget.download(lora_url)` and manually putting the images to the folder.

**Comment by charchit7** [comment]
It works! Thanks!

Could you please guide me how to use your provided code to run without colab? 
You have mentioned that you are following `MultiDiffusion` and have provided code there. So, do I just need to modify there?

Please let me know.

**Comment by littlewhitesea** [comment]
Happy to hear that.

Sure, our code is based on MultiDifffusion. If you check the inference code of [MultiDiffusion](https://github.com/omerbt/MultiDiffusion/blob/master/panorama.py) and our provided code, it is very easy to find that we add the **pre-denoising operations twice on the stitch block** and **global cropping operation** part.

Note that there is a big difference between MultiDiffusion and StitchDiffusion. MultiDiffusion utilizes a pre-trained latent diffusion model, while our StitchDiffusion adopts our customized latent diffusion model, which consists of our provided [LoRA](https://drive.google.com/file/d/1MiaG8v0ZmkTwwrzIEFtVoBj-Jjqi_5lz/view) and the pre-trained latent diffusion model.

Hence, if you want to use my provided code, you should firstly integrate the LoRA into a pre-trained latent diffusion model, and then use our provided inference code (Perhaps you need to do some minor modifications to make the variable names consistent.), it should work. That is what the google colab does.

If you don't know how to integrate the LoRA into a pre-trained latent diffusion model, I recommend you to learn the code in the google colab.

**Comment by charchit7** [comment]
Thank you so much @littlewhitesea. 

I'll ask my doubt after reading the codebase. Hope that's fine. Happy to integrate to some open-source lib too.
Thank you for the paper it was well written.
