### ISSUE TITLE
Is this real equirectangular panorama image?

### ISSUE THREAD

**Issue by zxcvfd13502** [littlewhitesea/StitchDiffusion#3]
Hi, I was wondering whether the equirectangular projection is always ensured, or the finetuned model just know how to generate images seems like equirectangular patch? If equirectangular projection is ensured, it can be decomposed into multiple perspective view images right? 

I have this question because I also tried similar things, to make Multi-Diffusion work with camera rotations. But I found the latents are very sensitive to warping operations. The results becomes terrible after several steps. I was wondering whether you have met the same problem? Do you find directly learning and generating equirectangular images helps to solve this problem?

**Comment by littlewhitesea** [comment]
Hi, if you consider a 360-degree panorama using equirectangular projection as an image with these properties: (1) width=2*height, (2) continuity between its leftmost and rightmost sides, (3) covering the entire 360° x 180° field of view, I would say that our method could synthesize this kind of image. I suggest you to run the [google colab](https://github.com/lshus/stitchdiffusion-colab), and then test whether the generated image can be decomposed into multiple perspective view images as expected.

I didn't use the warping operation in the latent space, so I didn't meet with this problem. In my opinion, if you just need to produce a static 360-degree panorama, generating equirectangular images should be helpful for your problem. (I am not sure that I fully understand your goal to make multi-diffusion work with camera rotations. If my suggestion doesn't work, just ignore it.)
