### ISSUE TITLE
Original images of training dataset

### ISSUE THREAD

**Issue by ByeongHyunPak** [littlewhitesea/StitchDiffusion#5]
Hi, I'm interested in your impressive work!

Could you provide the original images (before x8 downsampling) of training dataset?

Thank you!

**Comment by littlewhitesea** [comment]
Thanks for your interest.

You can find the [download link](https://drive.google.com/file/d/1RFfLH6zzwsd3rlRRxuN-RtBWv6BsWXMO/view?usp=sharing) of 8k 360-degree panoramas in the repository now.
